#This function takes one integer argument, n, and prints out a pair of numbers (i, j) for every possible combination of i and j in the range of 0 up to but not including n.
#Each pair (i, j) is printed on a new line. i and j iterate over the range independently, so every combination of i and j in the range should be printed.
#The output of the function should be a series of pairs, printed one after the other, each on a new line. The pairs should be printed in the order that they are generated by the nested loops.

def print_items(n):
    for i in range(n):
        for j in range(n):
            print(i,j) 

print_items(10)
#output
# 0 0
# 0 1
# 0 2
# 0 3
# 0 4
# 0 5
# 0 6
# 0 7
# 0 8
# 0 9
# 1 0
# 1 1
# 1 2
# 1 3
# 1 4
# 1 5
# 1 6
# 1 7
# 1 8
# 1 9
# 2 0
# 2 1
# 2 2
# 2 3
# 2 4
# 2 5
# 2 6
# 2 7
# 2 8
# 2 9
# 3 0
# 3 1
# 3 2
# 3 3
# 3 4
# ...
# 9 9
# The function prints n^2 pairs of numbers, resulting in n^2 outputs.
# The time complexity is O(n^2) because of the nested loops, each iterating n times.
# The space complexity is O(1) since no additional space is used that scales with input size.